# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [3]:
import numpy as np
np. __version__

'1.26.4'

2) Создать нулевой вектор размера 10

In [19]:
arr = np.full(10,0)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3) Создать вектор заполненный 7-ами размера 7

In [17]:
arr = np.full(7,7)
arr

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [22]:
arr = np.arange(10, 100, 2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [38]:
arr = np.array([1,2,3,4,5])
np.flip(arr)

array([5, 4, 3, 2, 1])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [41]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [46]:
arr = np.eye(4, k=1)
arr

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [52]:
arr = np.full((4, 4),7)
np.fill_diagonal(arr, np.arange(1, 5))
arr

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [56]:
arr = np.tile(np.arange(5),(5,1))
arr

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [9]:
arr = np.random.rand(10,10)*10//1
arr = arr - arr.mean(axis=1,keepdims=True)
arr

array([[ 1.1,  1.1, -1.9, -0.9, -2.9,  5.1, -1.9,  1.1, -3.9,  3.1],
       [-3.5, -2.5,  2.5,  3.5, -3.5,  4.5,  3.5, -0.5, -1.5, -2.5],
       [-4. ,  2. , -1. ,  2. ,  2. , -3. , -3. ,  4. ,  4. , -3. ],
       [-2.7, -2.7,  2.3,  1.3, -1.7, -0.7,  1.3, -0.7,  3.3,  0.3],
       [ 1.3, -1.7, -1.7,  0.3,  3.3,  3.3, -4.7,  3.3, -1.7, -1.7],
       [-4.7,  1.3,  1.3, -0.7, -0.7,  0.3, -2.7,  4.3, -1.7,  3.3],
       [ 3. ,  4. ,  2. ,  2. , -2. , -1. , -5. ,  1. , -4. ,  0. ],
       [-3.1, -2.1, -2.1,  2.9, -1.1, -2.1,  5.9, -0.1, -3.1,  4.9],
       [-4. , -3. , -1. ,  2. ,  4. ,  1. ,  0. ,  3. ,  2. , -4. ],
       [-2.1,  5.9, -1.1, -0.1, -3.1,  0.9, -2.1, -0.1,  4.9, -3.1]])

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [17]:
arr = np.random.rand(10,10)*10//1
arr = arr - np.median(arr,axis=0)
arr

array([[-3. , -4. ,  1. ,  1. ,  0.5, -1.5, -3.5, -5. ,  2.5, -3. ],
       [ 0. ,  2. , -1. ,  1. ,  1.5,  2.5, -3.5, -5. , -3.5,  4. ],
       [ 2. ,  1. ,  0. ,  3. , -2.5,  3.5,  5.5,  1. , -0.5, -5. ],
       [-2. , -1. ,  3. ,  0. ,  0.5,  0.5,  1.5, -4. ,  4.5, -4. ],
       [ 0. , -6. , -6. , -5. , -0.5, -1.5, -0.5,  0. ,  0.5,  1. ],
       [ 5. , -3. ,  0. , -3. ,  3.5,  7.5,  0.5,  3. , -3.5,  2. ],
       [ 0. ,  2. , -1. , -5. , -1.5,  1.5, -0.5,  0. ,  3.5,  3. ],
       [-2. ,  2. ,  2. ,  0. ,  4.5, -1.5,  3.5, -2. ,  2.5, -1. ],
       [ 6. ,  1. , -1. , -5. , -2.5, -0.5, -3.5,  0. , -0.5, -5. ],
       [ 3. , -4. ,  0. ,  2. , -0.5, -0.5,  5.5,  2. , -4.5,  1. ]])

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [20]:
arr = np.random.rand(5,5)*10//1
min = arr.min(axis=1,keepdims=True)
max = arr.max(axis=1,keepdims=True)
arr = np.hstack((arr,min,max))
arr

array([[3., 1., 2., 1., 7., 1., 7.],
       [1., 6., 5., 2., 5., 1., 6.],
       [7., 0., 8., 6., 2., 0., 8.],
       [9., 4., 3., 2., 6., 2., 9.],
       [7., 5., 1., 2., 4., 1., 7.]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [42]:
arr = np.arange(1,51)
odd = arr[arr%2 != 0]
even = arr[arr%2 == 0]
odd= odd.reshape(-1, 1)
even = even.reshape(1, -1)
prod = odd @ even
inverse_matrix = np.linalg.pinv(prod)
#Невозможно найти обратную матрица вырожденная

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [43]:
arr = np.zeros((8, 8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])